"""add is_archived to tasks

Revision ID: 0695e719334e
Revises: 4f0caad6d582
Create Date: 2026-07-22 09:10:41.785751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0695e719334e'
down_revision: Union[str, Sequence[str], None] = '4f0caad6d582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "tasks",
        sa.Column(
            "is_archived",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # Remove the default so future inserts use the SQLAlchemy model default
    op.alter_column(
        "tasks",
        "is_archived",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_archived')
    # ### end Alembic commands ###
