"""add soft delete support

Revision ID: 19121b5125b6
Revises: 6a6d5bd84fcc
Create Date: 2026-07-14 09:17:39.411259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19121b5125b6'
down_revision: Union[str, Sequence[str], None] = '6a6d5bd84fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'users', ['deleted_by'], ['id'])
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['deleted_by'], ['id'])
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['deleted_by'], ['id'])
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'deleted_by')
    op.drop_column('tasks', 'deleted_at')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'deleted_by')
    op.drop_column('projects', 'deleted_at')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'deleted_by')
    op.drop_column('organizations', 'deleted_at')
    # ### end Alembic commands ###
