"""add public uuid

Revision ID: 4f0caad6d582
Revises: e1da3339c4bf
Create Date: 2026-07-17 15:28:13.709196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0caad6d582'
down_revision: Union[str, Sequence[str], None] = 'e1da3339c4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.add_column('activity_logs', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_activity_logs_public_id'), 'activity_logs', ['public_id'], unique=True)
    op.add_column('comments', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_comments_public_id'), 'comments', ['public_id'], unique=True)
    op.add_column('invitations', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_invitations_public_id'), 'invitations', ['public_id'], unique=True)
    op.add_column('memberships', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_memberships_public_id'), 'memberships', ['public_id'], unique=True)
    op.add_column('organizations', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_organizations_public_id'), 'organizations', ['public_id'], unique=True)
    op.add_column('projects', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_projects_public_id'), 'projects', ['public_id'], unique=True)
    op.add_column('tasks', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_tasks_public_id'), 'tasks', ['public_id'], unique=True)
    op.add_column('users', sa.Column(
        "public_id",
        sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    ),)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.alter_column(
        "activity_logs",
        "public_id",
        server_default=None,
    )

    op.alter_column(
        "comments",
        "public_id",
        server_default=None,
    )

    op.alter_column(
        "invitations",
        "public_id",
        server_default=None,
    )

    op.alter_column(
        "memberships",
        "public_id",
        server_default=None,
    )

    op.alter_column(
        "organizations",
        "public_id",
        server_default=None,
    )

    op.alter_column(
        "projects",
        "public_id",
        server_default=None,
    )

    op.alter_column(
        "tasks",
        "public_id",
        server_default=None,
    )

    op.alter_column(
        "users",
        "public_id",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'public_id')
    op.drop_index(op.f('ix_tasks_public_id'), table_name='tasks')
    op.drop_column('tasks', 'public_id')
    op.drop_index(op.f('ix_projects_public_id'), table_name='projects')
    op.drop_column('projects', 'public_id')
    op.drop_index(op.f('ix_organizations_public_id'), table_name='organizations')
    op.drop_column('organizations', 'public_id')
    op.drop_index(op.f('ix_memberships_public_id'), table_name='memberships')
    op.drop_column('memberships', 'public_id')
    op.drop_index(op.f('ix_invitations_public_id'), table_name='invitations')
    op.drop_column('invitations', 'public_id')
    op.drop_index(op.f('ix_comments_public_id'), table_name='comments')
    op.drop_column('comments', 'public_id')
    op.drop_index(op.f('ix_activity_logs_public_id'), table_name='activity_logs')
    op.drop_column('activity_logs', 'public_id')
    # ### end Alembic commands ###
