"""add notification type and reference_id

Revision ID: 7c7b39fea624
Revises: 946455556da2
Create Date: 2026-08-29 19:33:35.706589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7b39fea624'
down_revision: Union[str, Sequence[str], None] = '946455556da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('reference_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
